services:
  # Express Web App Service (Free Tier)
  - type: web
    name: quizzard-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
